name = "cdn"
main = "src/index.ts"
compatibility_date = "2023-03-07"
send_metrics = false

account_id = "3cf96cf54e0a58f2ae5c0754f0154c3f"
workers_dev = false

kv_namespaces = [
    { binding = "CDN_USERS", id = "54de8d8ce1dd4793b2fe6e636c8c5eac" }
]

[[r2_buckets]]
binding = "CDN_BUCKET"
bucket_name = "cdn"
preview_bucket_name = "cdn"

[vars]
REDIRECT_URL = "https://seren.dev"
